### ISSUE TITLE
Crashes server

### ISSUE THREAD

**Issue by 00c** [SmallJoker/names_per_ip#2]
On recent minetest 0.4.14-dev /whois PlayerName cause server to crash, no errors in debug.

> 2016-10-20 01:13:26: ACTION[Server]: Evil invoked /whois, param=Wrinkles
> 2016-10-20 01:13:26: ACTION[Server]: Wrinkles uses replacer:replacer, pointing at [node under=-33,-30951,6 above=-33,-30951,5]
> 2016-10-20 01:13:26: ACTION[Server]: Wrinkles digs default:stone_with_iron at (-33,-30951,6)
> 2016-10-20 01:13:26: INFO[Main]: Players:
> 2016-10-20 01:13:26: INFO[Main]: \* Jabbie359    RemoteClient 4: m_blocks_sent.size()=0, m_blocks_sending.size()=10, m_nearest_unsent_d=0, m_excess_gotblocks=0
> 2016-10-20 01:13:26: INFO[Main]: \* Wrinkles RemoteClient 6: m_blocks_sent.size()=50, m_blocks_sending.size()=0, m_nearest_unsent_d=0, m_excess_gotblocks=0
> 2016-10-20 01:13:26: INFO[Main]: Players:
> 2016-10-20 01:13:26: INFO[Main]: \* Jabbie359    RemoteClient 4: m_blocks_sent.size()=0, m_blocks_sending.size()=10, m_nearest_unsent_d=0, m_excess_gotblocks=0
> 2016-10-20 01:13:26: INFO[Main]: Server destructing
> 2016-10-20 01:13:26: [Server]: static int ModApiServer::l_get_player_ip(lua_State_): peer was not found
> 2016-10-20 01:13:26: [Server]: static int ModApiServer::l_get_player_ip(lua_State_): peer was not found

---

**Comment by SmallJoker** [comment]
The command `/whois <player>` comes from [Calinou's version](https://forum.minetest.net/viewtopic.php?t=9768) of this mod.
However, this rather seems to be a core issue because there is no `minetest.get_player_ip` call in both mod sources.

EDIT: Please run `grep` (with params) on your installed mods to see if there's one that implements the `/whois` command.

**Comment by 00c** [comment]
i see one more mod, chat_next has whois

**Comment by 00c** [comment]
some more info. Running /whois OnMyName does not trigger crash, i see N/A. /ipnames whois PlayerName works fine, no crashes. I guess bug is in chat_next

**Comment by SmallJoker** [comment]
Closed due not related to names_per_ip.
